---
title: "Data Manipulation"
output: github_document
date: "2026-09-24"
---

```{r setup, include=FALSE}
library(tidyverse)
```
```{r}
litters_df =
  read_csv(file = "data_import_examples/FAS_litters.csv", 
           na = c("", "NA", ".")
           )

litters_df = janitor::clean_names(litters_df)
litters_df
```
Import second dataset. 

```{r}
pups_df = 
  read_csv(file = "data_import_examples/FAS_pups.csv", 
           na = c("", "NA", "."),
           skip = 3
           )
pups_df

pups_df = janitor::clean_names(pups_df)
```
```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)

select(litters_df, group:gd_of_birth)

select(litters_df, -pups_survive)

select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)

select(litters_df, starts_with("gd"))

select(litters_df, litter_number, pups_survive, everything())
```
```{r}
rename(litters_df, GROUP = group)

relocate(litters_df, litter_number, gd0_weight)
```

in the pups data, select litter nnumber, sex and PD ears.

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

##`filter` some rows

```{r}
filter(litters_df, gd_of_birth == 19)

filter(litters_df, pups_born_alive <= 5)

filter(litters_df, pups_born_alive != 6)

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, group %in% c("Con7", "Con8"), pups_born_alive < 7)

filter(litters_df, pups_born_alive < 4 | pups_born_alive < 7)

drop_na(litters_df, gd0_weight) #drop_na is a handy tool to drop missing values
```
```{r}
filter(pups_df, pd_walk < 11, sex == 2)
```
## `mutate` to change some columns
```{r}
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain ^2,
       group = str_to_lower(group))
```
```{r}
mutate(
  pups_df, 
  pd_walk_minus_7 = pd_walk - 7
)
```

```{r}
head(arrange(litters_df, group, pups_born_alive), 10)
```

The power of "and then" or "|>"
```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na = c("", "NA", ".")) |>
  janitor::clean_names()|>
  select(group, starts_with("gd")) |>
  drop_na() |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  )
```
```{r}
pups_df =
  read_csv("data_import_examples/FAS_pups.csv", skip = 3, na = c("", "NA", ".")) |>
  janitor::clean_names()|>
  drop_na() |>
  select(litter_number, starts_with("pd")) |>
  mutate(
    pd_walk_minus_7 = pd_walk - 7
    )
```
